Query Resource Health Alerts
Azure/Azure-Proactive-Resiliency-Library pull request #152
Opened 2023-12-06 17:15 UTC by anlucen

# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2023-12-07 04:16 UTC, oZakari requested changes
Overall, the PR looks good. I updated a couple of minor things so you'll have to update your local branch as a heads up. Apart from the query changes could you go through and provide the details listed out in the PR form above?

2023-12-07 04:16 UTC, oZakari commented on docs/content/services/monitoring/resource-health-alerts/code/msr-1.kql
Could you please update the query to adhere to guidelines mentioned here: https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries

2023-12-11 18:27 UTC, anlucen commented on docs/content/services/monitoring/resource-health-alerts/code/msr-1.kql
Hello @oZakari , thank you for the fixing. I added the details i was missing about the description for the query commit and pull request sent

2023-12-14 18:53 UTC, oZakari commented
Note from call yesterday: @anlucen to update form: 
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/30884663/85bb2672-0121-4534-9057-1e2a45a0269a)

2023-12-20 01:46 UTC, anlucen commented
@oZakari  it was added the description for the pull requested.

2024-01-05 18:15 UTC, oZakari approved these changes

2024-01-12 03:23 UTC, oZakari approved these changes

2024-01-12 16:56 UTC, ejhenry approved these changes
LGTM 👍

2024-01-12 16:56 UTC, merged