fixed query for vm-13
Azure/Azure-Proactive-Resiliency-Library pull request #153
Opened 2023-12-07 14:34 UTC by ReneHezser

# Overview/Summary

Fixed query for vm-13 recommendation. Tested with 1 and 2 NICs attached to a VM.

## Related Issues/Work Items

## This PR fixes/adds/changes/removes

1. the query for vm-13

### Breaking Changes

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2023-12-08 05:59 UTC, oZakari requested changes
Thanks for the fixes, @ReneHezser! Just a few minor changes to make and then it should be good to go.

2023-12-11 22:42 UTC, oZakari commented on docs/content/services/compute/virtual-machines/code/vm-13/vm-13.kql
> +| where isnotnull(properties.networkSecurityGroup)
Hey @ReneHezser, after re-reading the title and associated guidance. I think it makes more sense to change the title to something as follows: **VM-13 - VM network interfaces and associated subnets both have a Network Security Group (NSG) associated**

As these recommendations will eventually be incorporated into Azure Advisor, the query should be updated to only return network interfaces if that particular subnet has an NSG as well as the subnet that it sits within has an NSG. Otherwise, people may remove their NSG from the NIC while their subnet may also not have an NSG.

2023-12-14 10:57 UTC, ReneHezser commented on docs/content/services/compute/virtual-machines/code/vm-13/vm-13.kql
> +| where isnotnull(properties.networkSecurityGroup)
I've adjusted the query and index accordingly.

2023-12-14 17:34 UTC, oZakari commented
Hey @ReneHezser, I added some screenshots of the query results and it's returning my test vm that has an nsg added to one of the nics that has nsg, but does not have nsg on subnet. Can you take a look and correct when you get the chance please? Let me know if you need to test again.

2023-12-15 16:21 UTC, ReneHezser commented
Thanks for finding this issue with the query. I've sorted it out.

2024-01-03 18:32 UTC, tksh164 commented
This query misses taking the case that the network interface with NSG, and the subnet without NSG (the case of only the NIC has NSG).

The following part of the query catches both patterns correctly.

- **A**: Network interface: NSG, Subnet: n/a
- **B**: Network interface: NSG, Subnet: NSG

```
Resources
| where type =~ 'Microsoft.Network/networkInterfaces'
| where isnotnull(properties.networkSecurityGroup)
| mv-expand ipConfigurations = properties.ipConfigurations, nsg = properties.networkSecurityGroup
| project nicId = tostring(id), subnetId = tostring(ipConfigurations.properties.subnet.id), nsgName=split(nsg.id, '/')[8]
| parse kind=regex subnetId with '/virtualNetworks/' virtualNetwork '/subnets/' subnet
```

However, the following part of the query returns only NSGs that are associated to subnets.

```
Resources
| where type =~ 'Microsoft.Network/NetworkSecurityGroups' and isnotnull(properties.subnets)
| project name, resourceGroup, subnet=properties.subnets
| mv-expand subnet
| project subnetId=tostring(subnet.id)
```

The query joins both above tables with `kind=inner`. The result table has only matching rows from both tables. This means the result table has only the case of **B**.

In my understanding, the expected results of VM-13 are the following:

- Network interface: n/a, Subnet: n/a ... Should *NOT* include in the result.
- Network interface: n/a, Subnet: NSG ... Should *NOT* include in the result.
- Network interface: NSG, Subnet: n/a ... Should include in the result.
- Network interface: NSG, Subnet: NSG ... Should include in the result.

So, `kind=leftouter` is good, I think (= the query that before the last commit).

My alternative query for reference:

```
// Azure Resource Graph Query
// Find all Virtual Machines that have network interfaces with network security groups.
resources
| where type =~ "Microsoft.Network/networkInterfaces" and isnotnull(properties.virtualMachine.id)
| mv-expand ipConfiguration = properties.ipConfigurations
| project
    nicName = name,
    nsgNameOfNic = parse_path(tostring(properties.networkSecurityGroup.id)).Filename,
    lowerCaseSubnetIdOfNic = tolower(ipConfiguration.properties.subnet.id),
    lowerCaseVmIdOfNic = tolower(properties.virtualMachine.id)
| where isnotempty(nsgNameOfNic)
| join kind = leftouter (
    resources
    | where type =~ "Microsoft.Compute/virtualMachines"
    | project vmName = name, vmId = id, vmTags = tags, lowerCaseVmId = tolower(id)
    )
    on $left.lowerCaseVmIdOfNic == $right.lowerCaseVmId
| join kind = leftouter (
    resources
    | where type =~ "Microsoft.Network/virtualNetworks"
    | mv-expand subnet = properties.subnets
    | project
        vnetName = name,
        subneName = parse_path(tostring(subnet.id)).Filename,
        subnetNsgName = parse_path(tostring(subnet.properties.networkSecurityGroup.id)).Filename,
        lowerCaseSubnetId = tolower(subnet.id)
    )
    on $left.lowerCaseSubnetIdOfNic == $right.lowerCaseSubnetId
| extend
    tags = iif(isempty(vmTags), "{}", vmTags),
    param1 = strcat("NetworkInterface: ", nicName),
    param2 = strcat("NetworkInterfaceNSG: ", nsgNameOfNic),
    param3 = strcat("VNet/Subnet: ", vnetName, "/", subneName),
    param4 = strcat("SubnetNSG: ", iif(isempty(subnetNsgName), "n/a", subnetNsgName))
| project recommendationId = "vm-13", name = vmName, id = vmId, tags, param1, param2, param3, param4
```

2024-01-03 18:50 UTC, tksh164 commented
Sorry, I misunderstood the VM-13 requirement.

- https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machines/#vm-13---vm-network-interfaces-have-a-network-security-group-nsg-associated
    > Unless you have a specific reason to, we recommend that you associate a network security group to a subnet, or a network interface, but not both.

So, the query of this PR is looks fine in my environment.

2024-01-11 08:05 UTC, ReneHezser commented
@oZakari any progress on this PR?

2024-01-11 21:40 UTC, oZakari commented
> @oZakari any progress on this PR?

Sorry for the delay with this @renehezser. I did some additional testing, and it seems there is just a delay with the data associated to the subnets. I had to wait approximately 30 minutes for it to accurately reflect the changes in ARG, but it is working on my end now as well.

2024-01-11 21:41 UTC, oZakari approved these changes

2024-01-11 22:02 UTC, ejhenry approved these changes
LGTM 👍 Thanks @ReneHezser !

2024-01-11 22:02 UTC, merged