Updated KQL for VMSS Recommendations
Azure/Azure-Proactive-Resiliency-Library pull request #162
Opened 2023-12-13 00:49 UTC by terrymandin

# Overview/Summary

Updated the KQL for VMSS Recommendations

## Related Issues/Work Items

AB#[32301](https://dev.azure.com/CSUSolEng/Azure%20Infra%20Compute/_workitems/edit/32301)

## This PR fixes/adds/changes/removes

1.  New KQL for [VMSS-2 - Enable VMSS application health monitoring](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-2---enable-vmss-application-health-monitoring)
2. New KQL for [VMSS-3 - Enable Automatic Repair policy](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-3---enable-automatic-repair-policy)
3. Updated KQL for [VMSS-4 - Configure VMSS Autoscale to custom and configure the scaling metrics](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-4---configure-vmss-autoscale-to-custom-and-configure-the-scaling-metrics)
4. New KQL for [VMSS-9 - Set Patch orchestration options to Azure-orchestrated](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-9---set-patch-orchestration-options-to-azure-orchestrated)

### Breaking Changes

## As part of this Pull Request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ x] Ensured PR tests are passing
- [x ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2023-12-13 22:42 UTC, oZakari requested changes
Hi @terrymandin, thank you for your PR! Could you please also add screenshots for evidence to confirm that the queries are working as anticipated?

2023-12-15 19:07 UTC, terrymandin commented
# Evidence
[VMSS-1 - Deploy VMSS with Flex orchestration mode instead of Uniform](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-1---deploy-vmss-with-flex-orchestration-mode-instead-of-uniform)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/230fcec1-1a71-48ea-9f6f-c8a87d70a7f5)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/2a67da63-fdf4-4489-9b88-a7effab708a5)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/ba8c8fe6-d022-44c8-b14a-0a541830a5f3)

[VMSS-2 - Enable VMSS application health monitoring](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-2---enable-vmss-application-health-monitoring)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/90d81a67-f055-4046-a50b-29781f37c892)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/9e796a42-1fa3-4ccf-8afa-779fb514b8b4)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/7975f29d-2e13-4afa-b94c-42be0bcc40fe)

[VMSS-3 - Enable Automatic Repair policy](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-3---enable-automatic-repair-policy)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/872eb462-0b9b-41e1-bc86-8e20efe7cc85)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/8a3532c0-3e6a-486b-8393-e94cc8ea7103)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/344dc276-25af-4d8e-b597-f32d4ee1abd7)

[VMSS-4 - Configure VMSS Autoscale to custom and configure the scaling metrics](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-4---configure-vmss-autoscale-to-custom-and-configure-the-scaling-metrics)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/347dc074-fe3d-465c-9fc8-d691963a2b59)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/2f27a89d-ac63-4d00-998e-1f8a590c707b)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/33abf562-12e4-43b5-acb5-bf30cd74e278)

[VMSS-5 - Enable Predictive autoscale and configure at least for Forecast Only](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-5---enable-predictive-autoscale-and-configure-at-least-for-forecast-only)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/5f8a9c52-6f04-425f-9cde-9bcbced9baca)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/8219b2c5-8d94-4f35-a98a-2cb271897da1)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/cc1429fc-9b40-4b49-83cf-fa7478d53df2)

[VMSS-6 - Disable Force strictly even balance across zones to avoid scale in and out fail attempts](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-6---disable-force-strictly-even-balance-across-zones-to-avoid-scale-in-and-out-fail-attempts)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/00ddbc84-6b8a-4e74-ae40-f7327ada8c7b)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/3c8ee8b6-46ec-423d-a945-80ab42613f40)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/b4ab0dc4-c194-4435-bf93-21d1fa358744)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/f165db92-6efb-4d3a-a945-d03416264817)

[VMSS-7 - Configure Allocation Policy Spreading algorithm to Max Spreading](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-7---configure-allocation-policy-spreading-algorithm-to-max-spreading)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/85a4db27-8611-4071-8ee2-3bf3c8b80803)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/849f4aa7-5876-49a4-986a-aba434bd682e)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/2571fbb2-4b1a-431e-9017-79cda2f633e7)

[VMSS-8 - Deploy VMSS across availability zones with VMSS Flex](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-8---deploy-vmss-across-availability-zones-with-vmss-flex)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/756f882a-5dec-4733-83b4-1921d7cfce4d)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/ad3346d4-aaec-4c47-a44f-9abec045be72)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/a42a52c7-7774-407a-bd68-b475b7b99c6d)

[VMSS-9 - Set Patch orchestration options to Azure-orchestrated](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machine-scale-sets/#vmss-9---set-patch-orchestration-options-to-azure-orchestrated)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/c595bdca-4c1f-43e6-841b-df372276e9b4)

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/833055/0930b163-a093-4895-86b8-70eb8aaf7e03)


@oZakari

2023-12-18 21:52 UTC, oZakari approved these changes

2024-01-02 21:39 UTC, ejhenry approved these changes
LGTM. Thanks @terrymandin !

2024-01-02 21:41 UTC, merged