Update AKS Guidance
Azure/Azure-Proactive-Resiliency-Library pull request #172
Opened 2023-12-18 19:07 UTC by ibersanoMS

# Overview/Summary

Updated guidance for AKS to include [these items](https://microsoft-my.sharepoint.com/:x:/r/personal/maprado_microsoft_com/Documents/Azure%20Core/Resiliency/Documentation/Action%20Plan%20-%20Services%20Hub%20Backlog%20items%20-%20AKS%20-%20Template.xlsx?d=wb0c5024f548e4c29b61fddbf5b6852ab&csf=1&web=1&e=5TcTox)

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. Adds AKS guidance items 8-31

### Breaking Changes

None

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-01-08 15:26 UTC, ibersanoMS commented
Do yall need a screenshot for each ARG query I added? I tested them when I wrote up the guidance, but I can include screenshots of the output if needed.

2024-01-08 17:07 UTC, ejhenry commented
> Do yall need a screenshot for each ARG query I added? I tested them when I wrote up the guidance, but I can include screenshots of the output if needed.

Hi @ibersanoMS, thanks for the PR! Yes, please include a screenshot of successful testing of each query that has been added. Also, please include a brief comment in each ARG query explaining what it is doing.

2024-01-09 18:08 UTC, ibersanoMS commented
Screenshots for AKS queries 8,11 ,13,15, 20, 22, 23, 24, 27
[Azure PRR - AKS_8-31_Query Screenshots.zip](https://github.com/Azure/Azure-Proactive-Resiliency-Library/files/13877478/Azure.PRR.-.AKS_8-31_Query.Screenshots.zip)

2024-01-10 18:23 UTC, oZakari requested changes
Hi @ibersanoMS, great work on this PR and thank you! Just noted some recommendations that appear to be explicitly oriented towards security. Could you please go through these and either update the guidance to reflect how it impacts reliability or potentially pull them out if necessary?

2024-01-10 18:23 UTC, oZakari commented on docs/content/services/container/aks/_index.md
> +Use network policies to allow or deny traffic to pods. By default, all traffic is allowed between pods within a cluster. For improved security, define rules that limit pod communication. Network poli
Could you please clarify how this impacts reliability, it looks to be more aligned to WAF security pillar.

2024-01-10 18:23 UTC, oZakari commented on docs/content/services/container/aks/_index.md
> +It’s important to keep your AKS cluster secure for the applications that you run. Azure Policy makes it possible to manage and report on the compliance state of your Kubernetes clusters from one plac
Could you please adjust the wording here as well to incorporate impact to reliability.

2024-01-10 18:23 UTC, oZakari commented on docs/content/services/container/aks/_index.md
> +As you manage clusters in Azure Kubernetes Service (AKS), workload and data security is a key consideration. When you run multi-tenant clusters using logical isolation, you especially need to secure
This one probably is specific to security and not reliability, unless you disagree?

2024-01-10 18:23 UTC, oZakari commented on docs/content/services/container/aks/_index.md
> +### AKS-16 - Keep a consistent configuration between regions with the API Server Authorized IP Addresses
Same with this one as well?

2024-01-10 18:23 UTC, oZakari commented on docs/content/services/container/aks/_index.md
> +### AKS-23 - Configure the API server Public IP access for public clusters
This appears to be focused directly towards security and not reliability

2024-01-10 18:23 UTC, oZakari commented on docs/content/services/container/aks/_index.md
> +### AKS-28 - Use the Azure KeyVault provider for Secrets Store CSI Driver
Focused specifically towards security, please adjust wording to how it impacts reliability.

2024-01-11 14:36 UTC, ibersanoMS commented
@oZakari Thanks for going through my PR! Yes, I can go through make those edits. The reason the id doesn't display is because if you put the id first in the order of properties that get displayed, it hides the id when you turn on Formatted results. If you turn off Formatted results, it will show the id. For the screenshots I had that on to hide my subscription id.

2024-01-11 15:39 UTC, ibersanoMS commented on docs/content/services/container/aks/_index.md
> +Use network policies to allow or deny traffic to pods. By default, all traffic is allowed between pods within a cluster. For improved security, define rules that limit pod communication. Network poli
Removed

2024-01-11 15:39 UTC, ibersanoMS commented on docs/content/services/container/aks/_index.md
> +It’s important to keep your AKS cluster secure for the applications that you run. Azure Policy makes it possible to manage and report on the compliance state of your Kubernetes clusters from one plac
Adjusted wording

2024-01-11 15:39 UTC, ibersanoMS commented on docs/content/services/container/aks/_index.md
> +As you manage clusters in Azure Kubernetes Service (AKS), workload and data security is a key consideration. When you run multi-tenant clusters using logical isolation, you especially need to secure
Removed

2024-01-11 15:40 UTC, ibersanoMS commented on docs/content/services/container/aks/_index.md
> +### AKS-16 - Keep a consistent configuration between regions with the API Server Authorized IP Addresses
Removed

2024-01-11 15:40 UTC, ibersanoMS commented on docs/content/services/container/aks/_index.md
> +### AKS-23 - Configure the API server Public IP access for public clusters
Removed

2024-01-11 15:40 UTC, ibersanoMS commented on docs/content/services/container/aks/_index.md
> +### AKS-28 - Use the Azure KeyVault provider for Secrets Store CSI Driver
Removed

2024-01-11 15:44 UTC, ibersanoMS commented
New screenshots for now AKS 10, 12, 17, 19, 20 and 23
[Azure PRR - AKS_10_23_Query Screenshots.zip](https://github.com/Azure/Azure-Proactive-Resiliency-Library/files/13905336/Azure.PRR.-.AKS_10_23_Query.Screenshots.zip)

2024-01-11 18:51 UTC, oZakari approved these changes

2024-01-11 18:53 UTC, oZakari commented
Thanks much @ibersanoMS! Also, thanks for correcting me about the screenshots, didn't notice the formatting toggle :D

I have approved the PR.

2024-01-11 19:03 UTC, ejhenry reviewed
Thanks for the contribution @ibersanoMS! It looks as though several of the ARG queries are returning results both of resources that do align and resources that do not align to the recommendation. The queries should be written to only return resources that do not align to the recommendation. For example, we would want the AKS-12 query to only return clusters with local accounts enabled.

2024-01-11 20:04 UTC, ibersanoMS commented
Thanks @ejhenry! I updated the queries to only return the non-compliant clusters. Apologies - I missed that in the docs. I've attached new screenshots here.
[Azure PRR - AKS_10_23_Revised_Query Screenshots.zip](https://github.com/Azure/Azure-Proactive-Resiliency-Library/files/13907789/Azure.PRR.-.AKS_10_23_Revised_Query.Screenshots.zip)

2024-01-11 21:04 UTC, oZakari commented
Thanks for the call out @ibersanoMS, just created a separate PR as we agree that the query requirement was not clear in that regard: https://github.com/Azure/Azure-Proactive-Resiliency-Library/pull/208

2024-01-11 21:04 UTC, oZakari approved these changes

2024-01-11 21:19 UTC, ejhenry approved these changes
LGTM 👍 Thanks @ibersanoMS !

2024-01-11 21:19 UTC, merged