Resource graph query fix
Azure/Azure-Proactive-Resiliency-Library pull request #233
Opened 2024-01-25 10:34 UTC by ReneHezser

# Overview/Summary

Fixed the resource graph query

## Related Issues/Work Items

AB#32807

## This PR fixes/adds/changes/removes

1. add resource graph query

### Breaking Changes

none

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-01-25 10:34 UTC, ReneHezser commented
**afw-1**
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/5988767/dd8756e2-0bed-48aa-bb13-35e4c8acc37a)

2024-01-30 01:29 UTC, ejhenry commented on docs/content/services/networking/firewall/code/afw-1/afw-1.kql
> +| where type == 'microsoft.network/azurefirewalls' and (isnull(zones) or zones !contains(','))
```suggestion
| where type == 'microsoft.network/azurefirewalls'
| where array_length(zones) <= 1 or isnull(zones)
```

2024-01-30 23:41 UTC, ejhenry commented
@Azure/aprl-networking do you want to review this networking PR before @oZakari and I review?

2024-01-31 01:52 UTC, ehaslett commented
@ReneHezser  I am still seeing blank entries for afw-3.kql. I wonder if other alerts not related to AFW are getting pulled in unintentionally:

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/60371213/8a4c016e-2bec-4ff3-8281-e9e1e75f5781)

2024-01-31 01:54 UTC, ehaslett requested changes
@ReneHezser  I am still seeing blank entries for afw-3.kql. I wonder if other alerts not related to AFW are getting pulled in unintentionally:
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/60371213/66d24ef1-2a42-4621-86f9-e73948e0efef)

2024-02-10 02:58 UTC, oZakari commented on docs/content/services/networking/expressroute-gateway/code/ergw-5/ergw-5.kql
> +| project recommendationId = "afw-5", name, id = firewallId, param1 = "ddosProtectionPlan:false"
```suggestion
// under-development
```

2024-02-10 03:02 UTC, oZakari commented on docs/content/services/networking/expressroute-gateway/code/ergw-5/ergw-5.kql
> +| project recommendationId = "afw-5", name, id = firewallId, param1 = "ddosProtectionPlan:false"
```suggestion
// Azure Resource Graph Query
// List all in-scope Azure Firewall resources, where the VNet is not associated to a DDoS Protection Plan
resources
| where type == "microsoft.network/azurefirewalls"
| mv-expand properties.ipConfigurations
| project name, firewallId = id, vNet = substring(properties_ipConfigurations.properties.subnet.id, 0, indexof(properties_ipConfigurations.properties.subnet, "/subnet") - 7)
| join kind=fullouter (
    resources
    | where type == "microsoft.network/ddosprotectionplans"
    | mv-expand properties.virtualNetworks
    | extend vNet = tostring(properties_virtualNetworks.id)
    | project ddosProtectionPlan = id, vNet
    )
    on $left.vNet == $right.vNet
| where ddosProtectionPlan == ''
| project recommendationId = "afw-5", name, id = firewallId, param1 = "ddosProtectionPlan:false"
```

2024-02-12 17:31 UTC, ehaslett approved these changes
LGTM - thank you @oZakari

2024-02-12 17:31 UTC, merged