Added "Specialized Workload" - HPC contents to APRL
Azure/Azure-Proactive-Resiliency-Library pull request #247
Opened 2024-01-30 19:39 UTC by lapate

# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-01-31 19:26 UTC, oZakari requested changes
Thanks for the contribution @lapate, along with the adjusting the review items associated to this review. Could you also please update the PR form with the relevant description and go through the [ARG query guidance](http://localhost:1313/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries) to ensure all queries are in adherence. Once complete, please share screenshots of the results returned for all queries.

Thank you and please reach out if you have any questions!

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +Currently in all HPC Pack ARM templates we create the cluster share on one of the head node which is not high available as if that head node is down, the share will not be accessible to the HPC Servi
Please reword for clarity as it is a bit difficult to understand what is being stated and how it relates to the recommendation of 'Ensure Azure File shares are active'

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +With Azure Files, these file shares can be moved to Azure Files shares with SMB permissions to make them high available.
```suggestion
With Azure Files, the following file shares can be moved to Azure Files shares with SMB permissions to make them highly available:
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +**Category: Availability/Identity**
```suggestion
**Category: Availability**
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +**Category: Availability**
```suggestion
**Category: System Efficiency**
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +| [HPC-5 Automatically grow and shrink HPC Pack cluster resources](#hpc-5---automatically-grow-and-shrink-hpc-pack-cluster-resources)  | Medium |  Availability | Preview |       No        |
```suggestion
| [HPC-5 Automatically grow and shrink HPC Pack cluster resources](#hpc-5---automatically-grow-and-shrink-hpc-pack-cluster-resources)  | Medium |  System Efficiency | Preview |       No        |
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +By deploying Azure "burst" nodes (both Windows and Linux) in your HPC Pack cluster or creating your HPC Pack cluster in Azure, you can automatically grow or shrink the cluster's resources such as nod
Can you update the wording to reflect how this impacts reliability directly.

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +### HPC-6 - HPC Pack - Dealing with database failure
Like the storage account recommendation above, this recommendation seems to be generalized to creating highly available SQL database. Please remove unless there is anything specific that needs to be called out from an HPC perspective.

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +### HPC-7 - HPC Pack - Dealing with Head node failure
```suggestion
### HPC-7 - HPC Pack - Dealing with head node failure
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +| [HPC-7 HPC Pack - Dealing with Head node failure](#hpc-7---hpc-pack---dealing-with-head-node-failure)  | Medium |  Resiliency | Preview |       No        |
```suggestion
| [HPC-7 HPC Pack - Dealing with head node failure](#hpc-7---hpc-pack---dealing-with-head-node-failure)  | Medium |  Resiliency | Preview |       No        |
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +Set up at least 2 head nodes in a cluster. With this configuration, any head node failure will result in moving the active HPC Service from this head node to another.
```suggestion
Establish a cluster with a minimum of two head nodes. In the event of a head node failure, the active HPC Service will be automatically transferred from the affected head node to another functioning one.
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +Using HPC Pack Azure AD integration solution without having the cluster nodes joining any domain. Thus as long as the HPC Service has connectivity to the Azure AD service.
```suggestion
- Having a high available domain controller deployed with your HPC Pack Cluster in Azure

- Using Azure AD Domain service. During cluster deployment, you could just join all your cluster nodes into this domain and you get the high available domain service from Azure.

- Using HPC Pack Azure AD integration solution without having the cluster nodes joining any domain. Thus as long as the HPC Service has connectivity to the Azure AD service.
```

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +### HPC-8 - HPC Pack - Dealing with AD failure
Please adjust recommendation name to short snippet of what the recommendation is such as `Use HPC Pack Azure AD Integration or other highly available AD configuration`

2024-01-31 19:26 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +### HPC-7 - HPC Pack - Dealing with Head node failure
Also, change to what the recommendation is versus just a generalized scenario could be `Set up at least 2 head nodes in a cluster`

2024-02-01 23:33 UTC, lapate commented
@oZakari , Thanks for the review of the contents.  I have committed all the updates.

2024-02-02 16:57 UTC, oZakari commented
Thanks @lapate! Could you update the PR form with the description of the PR as link any work items you're team may have assigned you.

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/30884663/6db4a43e-c958-47ce-b612-3f5b4740a0da)

2024-02-05 03:09 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +For Cross-region disaster recovery and business continuity, Make sure ahead of time that the appropriate quotas are set for all user subscription Batch accounts, to allocate the required number of co
This looks to have been mistakenly resolved, but no changes appear to have been made to the recommendation guidance so unresolving.

2024-02-06 17:46 UTC, oZakari approved these changes
Thanks much @lapate!

2024-02-09 02:48 UTC, tksh164 reviewed
@lapate Thank you for your contribution! Added suggestions, could you check those?

2024-02-09 02:48 UTC, tksh164 commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +| [HPC-1 Monitor Batch account quota](#hpc-1---monitor-batch-account-quota)  | Medium |  Resiliency/Monitoring | Preview |       Yes        |
```suggestion
| [HPC-1 Monitor Batch account quota](#hpc-1---monitor-batch-account-quota)  | Medium |  Resiliency/Monitoring | Preview |       No        |
```

2024-02-09 02:48 UTC, tksh164 commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +| [HPC-2 Ensure File shares that stores jobs metadata are accessible from all head nodes](#hpc-2---ensure-file-shares-that-stores-jobs-metadata-are-accessible-from-all-head-nodes)  | High |  Resilien
```suggestion
| [HPC-2 Ensure File shares that stores jobs metadata are accessible from all head nodes](#hpc-2---ensure-file-shares-that-stores-jobs-metadata-are-accessible-from-all-head-nodes)  | High |  Resiliency/Monitoring | Preview |       No        |
```

2024-02-09 02:48 UTC, tksh164 commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +\\<HN3>\CcpSpoolDir
```suggestion
- `\\<HN3>\REMINST`
- `\\<HN3>\HpcServiceRegistration`
- `\\<HN3>\Runtime$`
- `\\<HN3>\TraceRepository`
- `\\<HN3>\Diagnostics`
- `\\<HN3>\CcpSpoolDir`
```

2024-02-09 02:57 UTC, tksh164 commented
@oZakari We also have to update the [services-abbreviations.csv](https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/services-abbreviations.csv). But cannot directly map HPC to the specific Azure resource type and the [CAF Abbreviation](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations). Any ideas?

2024-02-09 04:34 UTC, oZakari commented
> @oZakari We also have to update the [services-abbreviations.csv](https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/services-abbreviations.csv). But cannot directly map HPC to the specific Azure resource type and the [CAF Abbreviation](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations). Any ideas?

Good question, I assumed since it is generalized to a workload that we wouldn't add it that services list. However, I don't have a lot of experience with HPC workloads so hoping @lapate can add clarity to determine if it makes sense to add something specific to that list for HPC.

2024-02-09 12:47 UTC, tksh164 commented
> > @oZakari We also have to update the [services-abbreviations.csv](https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/services-abbreviations.csv). But cannot directly map HPC to the specific Azure resource type and the [CAF Abbreviation](https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations). Any ideas?
> 
> Good question, I assumed since it is generalized to a workload that we wouldn't add it that services list. However, I don't have a lot of experience with HPC workloads so hoping @lapate can add clarity to determine if it makes sense to add something specific to that list for HPC.

I just concerned the compatible with `wara-arg-runner.ps1` that use in WARAv3 because the script uses the `services-abbreviations.csv` in it. So, I quickly reviewed that script, it looks like the script will work well. (I have not actually tried it)

2024-02-09 12:55 UTC, tksh164 approved these changes
LGTM 👍

2024-02-09 17:05 UTC, merged