Added the following recommendations to Azure Site Recovery.
Azure/Azure-Proactive-Resiliency-Library pull request #263
Opened 2024-02-08 08:45 UTC by aalewismsft

1. ASR-3 - Monitor Source VMs for high data change rates
2. ASR-4 - Ensure sufficient resource quotas in the target region

# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-02-09 17:38 UTC, oZakari requested changes
Hi @aalewismsft, thanks for your additions to ASR! Please go through the comments below and complete the PR form. Once finished, feel free to request another review from me.

2024-02-09 17:38 UTC, oZakari commented on docs/content/services/compute/site-recovery/_index.md
> +### ASR-3 - Monitor Source VMs for high data change rates
```suggestion
### ASR-3 - Monitor source VMs for high data change rates
```

2024-02-09 17:38 UTC, oZakari commented on docs/content/services/compute/site-recovery/_index.md
> +Azure Site Recovery has limits on data change rates, depending on the type of disk. To see if this problem is recurring or temporary, find the data change rate of the affected virtual machine. Go to
```suggestion
Azure Site Recovery has limits on data change rates, depending on the type of disk. To determine if this is a recurring or temporary problem, find the data change rate of the affected virtual machine. Go to the source virtual machine and monitor the **OS Disk Write Bytes/Sec** and **Data Disk Write Bytes/Sec** metrics for OS and Data disks.
```

2024-02-09 17:38 UTC, oZakari commented on docs/content/services/compute/site-recovery/code/asr-3/asr-3.kql
Please review this contribution guidance to make sure your query adheres to all requirements: https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries

2024-02-09 17:38 UTC, oZakari commented on docs/content/services/compute/site-recovery/_index.md
As these are new recommendations, you will also need to update the table toward the top of this page.

2024-02-14 16:56 UTC, aalewismsft reviewed
Requested changes implemented.

2024-02-20 01:43 UTC, oZakari commented on docs/content/services/compute/site-recovery/_index.md
> +
```suggestion
```

2024-02-20 04:31 UTC, oZakari commented on docs/content/services/compute/site-recovery/code/asr-3/asr-3.kql
Hi @aalewismsft, could you review this query again and the link above to make sure that the required column names are included as well as any additional parameters show up as param1, param2, .... up to param5? 

Also, please update the PR form and include a screenshot of the query results.
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/30884663/5ff1b393-89f2-47ec-9d0a-6b874a57bebf)

2024-03-05 14:45 UTC, closed without merging