Rosanto Quality updates for VMs, Netapp, Batch Accounts, AVS
Azure/Azure-Proactive-Resiliency-Library pull request #273
Opened 2024-02-13 21:09 UTC by rodrigosantosms

# Overview/Summary

Rosanto Quality updates for VMs, Netapp, Batch Accounts, AVS

## Related Issues/Work Items

Rosanto Quality updates for VMs, Netapp, Batch Accounts, AVS

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. Rosanto Quality updates for VMs, Netapp, Batch Accounts, AVS

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-02-13 22:18 UTC, ejhenry commented on docs/content/services/compute/virtual-machines/_index.md
> +B-series VMs are ideal for workloads that do not need the full performance of the CPU continuously, like web servers, proof of concepts, small databases and development build environments. These work
```suggestion
B-series VMs are ideal for workloads that do not need the full performance of the CPU continuously, like web servers, proof of concepts, small databases and development build environments. These workloads typically have burstable performance requirements. To determine the physical hardware on which this size is deployed, query the virtual hardware from within the virtual machine. The B-series provides you with the ability to purchase a VM size with baseline performance that can build up credits when it is using less than its baseline. When the VM has accumulated credits, the VM can burst above the baseline using up to 100% of the vCPU when your application requires higher CPU performance. Upon consuming all the CPU credits, a B-series virtual machine is throttled back to its base CPU performance until it accumulates the credits to CPU burst again.
```

2024-02-13 22:28 UTC, ejhenry approved these changes
LGTM 👍

2024-02-14 00:26 UTC, oZakari commented on docs/content/services/compute/virtual-machines/_index.md
> -| [VM-15 - Customer DNS Servers should be configured in the Virtual Network level](#vm-15---dns-servers-should-be-configured-in-the-virtual-network-level)
Can you adjust the recommendation directly as well please. It wouldnt let me add a suggestion for that line.

2024-02-14 00:34 UTC, oZakari requested changes
Hey Rodrigo, could you also please change the acronym from bat to ba to align to the CAF documentation: https://learn.microsoft.com/en-us/azure/cloud-adoption-framework/ready/azure-best-practices/resource-abbreviations#compute-and-web

2024-02-15 06:09 UTC, rodrigosantosms commented on docs/content/services/compute/virtual-machines/_index.md
> -| [VM-15 - Customer DNS Servers should be configured in the Virtual Network level](#vm-15---dns-servers-should-be-configured-in-the-virtual-network-level)
I just updated the line 31.

2024-02-15 07:32 UTC, rodrigosantosms commented
@oZakari  the BuildPr job was failing due to a change on Feb/13 where the hugo theme was changed from ACE to a new one. I had to revert it, let's discuss it offline. Please review the other changes, great that you noticed a lot of things missing. thank  you

2024-02-15 16:08 UTC, oZakari commented
Hey Rodrigo, I had pulled it out of your branch. Looks like it may have already been synced with your local branch as it is back in. I'll pull it out.

2024-02-15 18:03 UTC, oZakari approved these changes

2024-02-15 18:03 UTC, merged