Updated AVS-1, AVS-2, AVS-3, added AVS-4, AVS-5, AVS-6, AVS-7
Azure/Azure-Proactive-Resiliency-Library pull request #296
Opened 2024-02-27 14:12 UTC by michielvanschaik

# Overview/Summary

Update to AVS recommendations, 3 updated, 4 added.

## Related Issues/Work Items

DevOps Work Item: https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVS/_workitems/edit/31681

## This PR fixes/adds/changes/removes

1. Updated AVS-1
2. Updated AVS-2
3. Updated AVS-3
4. Added AVS-4
5. Added AVS-5
6. Added AVS-6
7. Added AVS-7

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-02-27 15:04 UTC, sblair01 approved these changes

2024-02-27 16:11 UTC, ejhenry reviewed
@michielvanschaik and @sblair01 thanks for the contribution!

We are not re-using recommendation IDs because we have downstream consumers that are expecting them to remain unchanged. As AVS1-3 all look like new recommendations we will want to use new IDs. If the current AVS1-3 are no longer needed, please remove them.

2024-02-27 22:58 UTC, oZakari requested changes

2024-02-27 22:58 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
> +|[AVS-9 Apply Resource lock on the resource group hosting the private cloud](#avs-9---apply-resource-lock-on-the-resource-group-hosting-the-private-cloud) | Governance | High | Preview | No |
```suggestion
|[AVS-3 Configure Azure Monitor Alert warning thresholds for vSAN datastore consumption](#avs-3---configure-azure-monitor-alert-warning-thresholds-for-vsan-datastore-consumption) | Monitoring | High | Preview | No |
|[AVS-4 Enable Stretched Clusters for High Availability of the vSAN Datastore](#avs-4---enable-stretched-clusters-for-high-availability-of-the-vsan-datastore) | Availability | Low | Preview | No |
|[AVS-5 Monitor CPU Utilization to ensure sufficient resources](#avs-5---monitor-cpu-utilization-to-ensure-sufficient-resources) | Monitoring | Medium | Preview | No |
|[AVS-6 Monitor Memory Utilization to ensure sufficient resources](#avs-6---monitor-memory-utilization-to-ensure-sufficient-resources) | Monitoring | Medium | Preview | No |
|[AVS-7 Monitor when  AVS Cluster Size is approaching the host limit](#avs-7---monitor-when-avs-cluster-size-is-approaching-the-host-limit) | Monitoring | Medium | Preview | No |
|[AVS-8 Monitor when AVS Private Cloud is reaching capacity](#avs-8---monitor-when-avs-private-cloud-is-reaching-capacity) | Monitoring | Medium | Preview | No |
|[AVS-9 Apply Resource lock on the resource group hosting the private cloud](#avs-9---apply-resource-lock-on-the-resource-group-hosting-the-private-cloud) | Governance | High | Preview | No |
```

2024-02-27 23:00 UTC, oZakari approved these changes

2024-02-28 00:55 UTC, ejhenry approved these changes
LGTM 👍

2024-02-28 00:55 UTC, merged