rosanto - quality updates - adding tags, fixing issues
Azure/Azure-Proactive-Resiliency-Library pull request #314
Opened 2024-03-06 22:56 UTC by rodrigosantosms

# Overview/Summary

rosanto - quality updates - adding tags, fixing issues

## Related Issues/Work Items

rosanto - quality updates - adding tags, fixing issues

## This PR fixes/adds/changes/removes

rosanto - quality updates - adding tags, fixing issues

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-03-07 14:48 UTC, JefferyMitchell commented
@rodrigosantosms Advisor team has asked that all ARG quires contain subscription ID and Resource ID for advisor. Can they update our queries on APRL to do so or would that break our automation?

2024-03-07 16:29 UTC, rodrigosantosms commented
> @rodrigosantosms Advisor team has asked that all ARG quires contain subscription ID and Resource ID for advisor. Can they update our queries on APRL to do so or would that break our automation?

All ARGs today already output the ResourceID which contains SubscriptionID too. Yes anybody from Microsoft can update our Queries and submit PRs.

2024-03-07 17:53 UTC, JefferyMitchell approved these changes
Approving with additional reviews from others in the workload team to look at DDOS and Resolver.

2024-03-08 04:14 UTC, oZakari requested changes

2024-03-08 04:14 UTC, oZakari commented on docs/content/services/compute/virtual-machine-scale-sets/code/vmss-11/vmss-11.kql
> +| project recommendationId = "vmss-11", name, id, tags
I know you tested the queries and I don't mean to be a pain. However, as this is a new query and to consistent in our review process could you please add a screenshot?

2024-03-08 04:14 UTC, oZakari commented on docs/content/services/web/web-app/code/app-6/app-6.kql
Can you please add screenshot for this as well?

2024-03-08 16:13 UTC, rodrigosantosms commented on docs/content/services/compute/virtual-machine-scale-sets/code/vmss-11/vmss-11.kql
> +| project recommendationId = "vmss-11", name, id, tags
Replied internally.

2024-03-08 19:36 UTC, ehaslett approved these changes
LGTM

2024-03-08 19:48 UTC, oZakari commented on docs/content/services/web/web-app/code/app-6/app-6.kql
Rodrigo shared screenshot in Teams.

2024-03-08 19:48 UTC, oZakari approved these changes

2024-03-08 19:48 UTC, merged