Updating PIP-1
Azure/Azure-Proactive-Resiliency-Library pull request #328
Opened 2024-03-13 22:20 UTC by jhajduk-microsoft

# Overview/Summary

Updating PIP-1 with ARG query

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [X] Ensured PR tests are passing
- [X] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-03-14 00:32 UTC, ejhenry reviewed
Thanks for the contribution @jhajduk-microsoft! Can you please include a check in the query for Standard SKU IPs that are not zone-redundant, and include a screenshot of your query test results in the PR?

2024-03-14 02:41 UTC, ehaslett requested changes

2024-03-14 02:41 UTC, ehaslett commented on docs/content/services/networking/public-ip/code/pip-1/pip-1.kql
This is good to check if a PIP is not a standard SKU and report this, but it should also check PIPs that are Standard SKU but not zone-redundant and present those as well.

2024-03-14 05:51 UTC, tksh164 commented
@jhajduk-microsoft @ejhenry - The ARG query looks the same as [pip-1.kql.fix](https://github.com/Azure/Azure-Proactive-Resiliency-Library/blob/main/docs/content/services/networking/public-ip/code/pip-1/pip-1.kql.fix) file. Also, PIP-1 recommendation revised on #301 

Standard Public IPs have possibility that non-zonal and zonal even if Standard SKU.
- [Test case for PIP-1](https://github.com/tksh164/aprl-testing/tree/main/services/networking/public-ip/test/pip-1)

On other hand, we should add a new recommendation for "Upgrade Basic SKU to Standard SKU".

- [Upgrade a public IP address using the Azure portal](https://learn.microsoft.com/en-us/azure/virtual-network/ip-services/public-ip-upgrade-portal)

2024-03-14 16:11 UTC, jhajduk-microsoft commented
@tksh164 - I thought it was odd that the query already existed. I am not part of the team that maintains this so not sure what the fix files are for so did not know the ask was revised. I will add the zonal check

2024-03-14 16:20 UTC, jhajduk-microsoft commented
<img width="1209" alt="image" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/77755957/3b71371d-48fd-4870-a8f8-592021cc588e">

2024-03-14 22:53 UTC, ejhenry reviewed
The query as currently written does not return Standard sku PIPs that are not zone-redundant.  We need to catch these as well to identify them for customers as not being aligned with the recommendation.

2024-03-15 05:40 UTC, tksh164 commented
@jhajduk-microsoft - FYI regarding `.fix` file.

- [Azure Resource Graph (ARG) Queries - Contribution guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries)
> 5. If a ARG query folder has a file with a file type suffixed with .fix, this means that the current query does not work as anticipated and to consider using this as a starting point for fixing the query. Once you have validated that the query is working as anticipated, please remove the file with the .fix suffix.

2024-03-15 17:14 UTC, jhajduk-microsoft commented
@tksh164 - Thanks so much! That helps with context. I have also submitted the changes as required. Please let me know if further changes are needed. @ejhenry

2024-03-15 17:33 UTC, ejhenry commented
> @tksh164 - Thanks so much! That helps with context. I have also submitted the changes as required. Please let me know if further changes are needed. @ejhenry

@jhajduk-microsoft - The query as currently written does not return Standard sku PIPs that are not zone-redundant. We need to catch these as well to identify them for customers as not being aligned with the recommendation.

2024-03-15 17:36 UTC, jhajduk-microsoft commented
@ejhenry - I updated and pushed my branch - is it now showing?

2024-03-15 17:39 UTC, jhajduk-microsoft commented
@ejhenry - NVM, got it, updating now

2024-03-15 19:22 UTC, ejhenry commented
@jhajduk-microsoft - there a three PIP configs we need to return with the query that do not align with the recommendation:

1. Basic PIP
2. Standard PIP - no zone
3. Standard PIP - single zone

The current version of the query is only catching the second config on the list.

2024-03-15 19:44 UTC, jhajduk-microsoft commented
Thanks for clearing that up. Here is the screenshot:
<img width="1230" alt="image" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/77755957/3ec66253-aa53-4fd0-8166-07b1c94b91e2">

2024-03-15 23:26 UTC, ejhenry approved these changes
LGTM 👍

2024-03-16 02:04 UTC, tksh164 commented
@jhajduk-microsoft - Could you change the column name `zones` to `param2`? because `zones` is not valid column name.

- [Azure Resource Graph (ARG) Queries - Contribution guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#azure-resource-graph-arg-queries)
> 6. ARG query columns name returned should only include the following:

2024-03-18 15:53 UTC, jhajduk-microsoft commented
I have updated the param:
<img width="1228" alt="image" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/77755957/00cb7cde-ef79-45ff-943f-156f3c1e5e04">

2024-03-18 21:05 UTC, rodrigosantosms reviewed
Approved. Improvements will be made by the team to improve the query later.

2024-03-18 23:49 UTC, merged