TRAF 1-4 KQL
Azure/Azure-Proactive-Resiliency-Library pull request #329
Opened 2024-03-14 01:11 UTC by Monte-Hazboun

# Overview/Summary

Added KQL for TRAF 1-4.  1, 2, and 4 are pretty straightforward but 3 can get messy when trying to consider edge cases for external (non-azure native) endpoints.  For example, if a customer puts an IP address as an external endpoint we have to walk through each use case and find the associated IP's resource (which could very well not even be something in Azure) to determine it's location.  If the customer puts an FQDN as an external resource it's even harder to find the associated resource if one exists.    The query for TRAF-3 is based on my best effort to consider every resource that might have an IP address and walk through them.  Given all of the edge cases, I expect this query to not work correctly in some amount of cases and I wouldn't fault anyone for marking TRAF-3 as cannot be validated with an arg.  I'm also open to discussing alternatives that anyone can think of.

## Related Issues/Work Items

N/A

## This PR fixes/adds/changes/removes

1. TRAF-1 KQL
2. TRAF-2 KQL
3. TRAF-3 KQL
4. TRAF-4 KQL

<img width="1660" alt="TRAF-1" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/20292838/47e19fcd-887e-4b17-978c-213e4973df27">

<img width="1646" alt="traf-2" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/20292838/7d95cfba-212a-4ee0-9ed4-197e4ce8ddf8">

<img width="1641" alt="traf-3" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/20292838/2f83f4e2-5ea9-4a65-98ea-25d464a3cce2">

<img width="1625" alt="traf-4" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/20292838/54694c08-0aa6-4b11-ae5c-ba5cc861bf54">

## As part of this Pull Request I have

- [X] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [X] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [X] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [X] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [X] Ensured PR tests are passing
- [X] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [X] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-03-14 16:54 UTC, ejhenry reviewed
Thanks @Monte-Hazboun! The queries look good to me. 

Regarding traf-3, I'm questioning whether this should be a TM recommendation at all. Seems like it would be redundant with recommendations we'll already be making for multi-region deployments related to the endpoints.

@Azure/aprl-networking - thoughts on traf-3?

2024-03-15 02:42 UTC, Monte-Hazboun commented
> Regarding traf-3, I'm questioning whether this should be a TM recommendation at all. Seems like it would be redundant with recommendations we'll already be making for multi-region deployments related to the endpoints.
> 

I think the recommendation makes sense, it's not really covered by any other recommendation.  I think traf-2 and traf-3 can be combined into a single recommendation.  2 (Traffic manager profiles should have more than one endpoint) is sort of redundant when you check 3 (configure at least one endpoint within another region).  

How do the owners feel about queries that don't solve every case?  The other option we have is to limit the query to only Azure endpoints, with a note perhaps as a param to manually check if there's an external endpoint in the TM profile.

2024-03-18 14:53 UTC, ejhenry commented
@Azure/aprl-networking please review

2024-03-21 00:10 UTC, ejhenry commented
@Monte-Hazboun thanks again for your contributions! The decision has been made to remove the TRAF-3 recommendation entirely. If you want to pull the TRAF-3 query from this PR, I can follow up to remove the recommendation from the index page.

2024-03-21 05:43 UTC, Monte-Hazboun commented
> @Monte-Hazboun thanks again for your contributions! The decision has been made to remove the TRAF-3 recommendation entirely. If you want to pull the TRAF-3 query from this PR, I can follow up to remove the recommendation from the index page.

@ejhenry - removed traf-3 query, replaced with a recommendation no longer valid message. Let me know if you want me to delete completely and shift the other recommendations up.

2024-03-21 14:51 UTC, ejhenry commented on docs/content/services/networking/traffic-manager/code/traf-3/traf-3.kql
> +// This recommendation to be removed from the aprl
```suggestion
// cannot-be-validated-with-arg

```

2024-03-21 14:55 UTC, ejhenry approved these changes
LGTM 👍

2024-03-21 23:58 UTC, davenewman777 commented
As a part of TRAF-1 as it stands, the query will still pull resources that are Online. It will pull all the endpoints. 
This will work better:
resources
| where type =~ "microsoft.network/trafficmanagerprofiles"
| mv-expand properties.endpoints
| where properties**_**endpoints.properties.endpointMonitorStatus != "Online"
| project recommendationId = "TRAF-1", name, id, tags, param1 = strcat('Profile name: ',properties**_**endpoints.name), param2 = strcat('endpointMonitorStatus: ',properties_endpoints.properties.endpointMonitorStatus)

replace the first dot in line 4 with an _ character. The same with the first underscore in line 5 so that it is properties_endpoints not properties.endpoints

2024-03-22 00:17 UTC, Monte-Hazboun commented
> As a part of TRAF-1 as it stands, the query will still pull resources that are Online. It will pull all the endpoints. This will work better: resources | where type =~ "microsoft.network/trafficmanagerprofiles" | mv-expand properties.endpoints | where properties**_**endpoints.properties.endpointMonitorStatus != "Online" | project recommendationId = "TRAF-1", name, id, tags, param1 = strcat('Profile name: ',properties**_**endpoints.name), param2 = strcat('endpointMonitorStatus: ',properties_endpoints.properties.endpointMonitorStatus)
> 
> replace the first dot in line 4 with an _ character. The same with the first underscore in line 5 so that it is properties_endpoints not properties.endpoints

Thanks for the feedback @davenewman777 but I'm not tracking.   Just want to make sure I'm understanding - you want me to change: 

```
resources
| where type == "microsoft.network/trafficmanagerprofiles"
| mv-expand properties.endpoints
| where properties_endpoints.properties.endpointMonitorStatus != "Online"
| project recommendationId = "traf-1", name, id, tags, param1 = strcat('Profile name: ',properties_endpoints.name), param2 = strcat('endpointMonitorStatus: ', properties_endpoints.properties.endpointMonitorStatus)
```

to 

```
resources
| where type == "microsoft.network/trafficmanagerprofiles"
| mv-expand properties.endpoints
| where properties_endpoints_properties.endpointMonitorStatus != "Online"
| project recommendationId = "traf-1", name, id, tags, param1 = strcat('Profile name: ',properties.endpoints.name), param2 = strcat('endpointMonitorStatus: ', properties_endpoints.properties.endpointMonitorStatus)
```

The first change produces a syntax error and the second change isn't a valid property for the endpoint name.   I think I see the confusion though.  Param1 should be endpoint name:  and not profile name:  - does that make more sense?

2024-03-22 15:49 UTC, DaFitRobsta requested changes
Please review my comments for traf-4

2024-03-22 15:49 UTC, DaFitRobsta commented on docs/content/services/networking/traffic-manager/code/traf-4/traf-4.kql
> +| project recommendationId = "traf-4", name, id, tags, param1 = strcat('TTL: ', properties.dnsconfig.ttl)
properties.dnsconfig.ttl is case sensitive when performing the value comparison and projecting it as output. When running this query, it didn't return the results I expected. 
By updating with the case sensitive property name, it did work. 
Here's the updated KQL:
resources
| where type == "microsoft.network/trafficmanagerprofiles"
| where properties.dnsConfig.ttl != 60
| project recommendationId = "traf-4", name, id, tags, param1 = strcat('TTL: ', properties.dnsConfig.ttl)

Please verify and if you agree, please update the KQL.

2024-03-22 16:23 UTC, davenewman777 commented
Hi Monte - the mv-expand function separates the two array elements and creates another field called properties_endpoints. The properties_endpoints field contains just the data for one endpoint. The properties.endpoint object still contains all the endpoints and when you use that in the where clause on line 4, you will get a line response for all endpoints, even if they don't match the where clause. By using the properties_endpoints field, the query is matching the where command against each individual endpoint instead of the array of endpoints. 
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/95712677/59566e4d-4cde-421f-bb5c-58c6ba6ce675)
I do not get any errors running this query

2024-03-22 16:27 UTC, davenewman777 commented
resources
| where type =~ "microsoft.network/trafficmanagerprofiles"
| mv-expand properties.endpoints
| where properties_endpoints.properties.endpointMonitorStatus != "Online"
| project recommendationId = "TRAF-1", name, id, tags, param1 = strcat('Profile name: ',properties_endpoints.name), param2 = strcat('endpointMonitorStatus: ',properties_endpoints.properties.endpointMonitorStatus)

2024-03-22 16:31 UTC, Monte-Hazboun commented on docs/content/services/networking/traffic-manager/code/traf-4/traf-4.kql
> +| project recommendationId = "traf-4", name, id, tags, param1 = strcat('TTL: ', properties.dnsconfig.ttl)
Not sure how this changed from my screenshot to the code, but good catch!  fixed.

2024-03-22 16:52 UTC, DaFitRobsta approved these changes
LGTM

2024-03-22 16:54 UTC, Monte-Hazboun commented
Thanks again @davenewman777 - your screenshot and query matches what I already have in the branch.  Do you still feel that I need to make changes or are we good to go?

2024-03-22 17:40 UTC, ejhenry commented
Confirmed with @davenewman777 we are good to go. Thanks again @Monte-Hazboun for the contribution! I will merge.

2024-03-22 17:40 UTC, merged