Additional AVS entries for AVS[10-15]
Azure/Azure-Proactive-Resiliency-Library pull request #330
Opened 2024-03-14 01:15 UTC by sblair01

# Overview/Summary

Additional AVS entries for AVS[10-15] 

## This PR fixes/adds/changes/removes

1. Changes Service Health from medium to high
2. Add AVS 10-15 to address availability, networking, disaster recovery, and identity and access management
3. Update some learn more links with relevant descriptions
4. Address some typos and language in the existing APRL queries

2024-03-14 09:17 UTC, michielvanschaik commented
@sblair01 can you also add the code files for AVS-10 to AVS-15 with "// under-development" in the kql?

2024-03-18 20:15 UTC, ejhenry approved these changes
LGTM

2024-03-19 17:59 UTC, oZakari requested changes
Please review my suggestions and incorporate if you agreed.

2024-03-19 17:59 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
> +<br><be>
```suggestion
<br><br>
```

2024-03-19 17:59 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
> +<br><be>
```suggestion
<br><br>
```

2024-03-19 17:59 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
> +<br><be>
```suggestion
<br><br>
```

2024-03-19 17:59 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
> +<br><be>
```suggestion
<br><br>
```

2024-03-19 17:59 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
> +If a Multi-AZ deployment of Azure VMware Solution is required, needs an infrastructure SLA of 99.99%, or needs synchronous storage replication between AZs (RPO=0), then Azure VMware Solution Stretche
```suggestion
If a Multi-AZ deployment of Azure VMware Solution is required, needs a financially backed SLA of 99.99%, or needs synchronous storage replication between AZs (RPO=0), then Azure VMware Solution Stretched Clusters should be considered. If you are in a region that supports stretched clusters, consider enabling this feature to spread the VMware vSAN datastore across two availability zones. Note: Configuring an Azure VMware Solution private cloud as a stretched cluster can only be done during initial implementation and requires twice the quota. This is due to a stretched cluster extending the cluster to the second availability zone.
```

2024-03-19 17:59 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-vmware-solution/_index.md
> +Alert when the cluster size of 14 hosts is reached. Periodically fire up alerts to plan for a new cluster or additional datastore if growth is driven solely by storage. Beyond 14 hosts, every time a
```suggestion
Alert when the cluster size of 14 hosts is reached. Additionally, periodic alerts should be set up to indicate when growth, especially driven by storage requirements, necessitates planning for a new cluster or the addition of extra datastores. Furthermore, beyond the threshold of 14 hosts, alerts should be triggered each time a new host is added to the cluster, allowing proactive monitoring and management of resource utilization.
```

2024-03-21 16:59 UTC, oZakari commented
Closing this PR as requested by @michielvanschaik.

cc: @sblair01

2024-03-21 16:59 UTC, closed without merging