Adding HPC recommendations
Azure/Azure-Proactive-Resiliency-Library pull request #340
Opened 2024-03-14 21:53 UTC by oZakari

# Overview/Summary

This is re-adding the HPC Pack recommendations into the HPC Specialized workload sections which was previously removed.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

-N/A

## This PR fixes/adds/changes/removes

1. Adding back the HPC specialized workload section
2. Adding all HPC-Pack recommendations that were previously removed from[ Azure Batch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pull/298). 

### Breaking Changes

1. None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-03-14 21:55 UTC, oZakari commented
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/30884663/be07c71c-06c1-4b52-8bcb-bfee65725593)
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/30884663/0bd35f10-eca4-41a0-b9f3-481b6ce55aa8)

2024-03-14 22:37 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +| [HPC-1 - Ensure File shares that stores jobs metadata are accessible from all head nodes](#hpc-1---ensure-file-shares-that-stores-jobs-metadata-are-accessible-from-all-head-nodes) | High | Resilien
```suggestion
| [HPC-1 - Ensure File shares that stores jobs metadata are accessible from all head nodes](#hpc-1---ensure-file-shares-that-stores-jobs-metadata-are-accessible-from-all-head-nodes) | High | Application Resilience | Preview | No |
```

2024-03-14 22:37 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +| [HPC-3 - Use multiple head nodes for HPC Pack](#hpc-3---use-multiple-head-nodes-for-hpc-pack) | Medium | Resiliency | Preview | No |
```suggestion
| [HPC-3 - Use multiple head nodes for HPC Pack](#hpc-3---use-multiple-head-nodes-for-hpc-pack) | Medium | Application Resilience | Preview | No |
```

2024-03-14 22:37 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +| [HPC-4 - Use HPC Pack Azure AD Integration or other highly available AD configuration](#hpc-4---use-hpc-pack-azure-ad-integration-or-other-highly-available-ad-configuration) | High | Resiliency | P
```suggestion
| [HPC-4 - Use HPC Pack Azure AD Integration or other highly available AD configuration](#hpc-4---use-hpc-pack-azure-ad-integration-or-other-highly-available-ad-configuration) | High | Application Resilience | Preview | No |
```

2024-03-14 22:37 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +**Category: Application Resilience/Availability**
```suggestion
**Category: Application Resilience**
```

2024-03-14 22:37 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +**Category: Resiliency**
```suggestion
**Category: Application Resilience**
```

2024-03-14 22:37 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-hpc/_index.md
> +**Category: Resiliency**
```suggestion
**Category: Application Resilience**
```

2024-03-14 22:39 UTC, ejhenry approved these changes
LGTM 👍

2024-03-15 20:13 UTC, Rajani-Janaki-Ram requested changes
Can we also cross link to the Batch ones (https://azure.github.io/Azure-Proactive-Resiliency-Library/services/batch/batch-accounts) in the table on this main page:

2024-03-18 17:22 UTC, oZakari commented
@Rajani-Janaki-Ram, I have added them, please let me know if you need anything else.

2024-03-19 17:16 UTC, Rajani-Janaki-Ram approved these changes

2024-03-19 17:17 UTC, merged