APIM -APRL recommendation
Azure/Azure-Proactive-Resiliency-Library pull request #346
Opened 2024-03-15 20:48 UTC by aarthiem

# Overview/Summary

APIM -APRL recommendation  for stv2 APIM upgrades

## Related Issues/Work Items
https://dev.azure.com/CSUSolEng/Well-Architected%20Framework/_workitems/edit/29872

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. adds recommendation for stv2 APIM upgrades

### Breaking Changes

1. NA

## As part of this Pull Request I have

- [ x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ x] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-03-15 23:54 UTC, ejhenry commented
Thanks for the contribution @aarthiem! Are you able to work through the failed linting check or do you need help with that?

2024-03-16 03:40 UTC, ejhenry commented on docs/content/services/integration/api-management/code/apim-3/apim-3.kql
> +| project recommendationId = "apim-3", name, id, tags, param1=strcat("Platform Version: ", plat_version) , param2=strcat("SKU: ", skuName)
```suggestion
| project recommendationId = "apim-3", name, id, tags, param1=strcat("Platform Version: ", plat_version) , param2=strcat("SKU: ", skuName)

```

2024-03-16 03:47 UTC, ejhenry commented on docs/content/services/integration/api-management/_index.md
> +<br><br>
```suggestion
<br><br>

```

2024-03-16 03:58 UTC, ejhenry commented
@aarthiem - I resolved the linting issues. Can you include in the PR a screenshot of the successful testing of your ARG query?

2024-03-21 18:39 UTC, ejhenry reviewed
Hi @aarthiem - Please update the summary table to include the new recommendation. 

I suggested a category from the allowed list in the contribution guide. If you think one of the other options would be a better fit, please change to that.

Also, please include a screenshot of the successful testing of your query.

2024-03-21 18:39 UTC, ejhenry commented on docs/content/services/integration/api-management/_index.md
> +**Category: Compliance**
```suggestion
**Category: Availability**
```

2024-03-22 23:15 UTC, aarthiem commented on docs/content/services/integration/api-management/_index.md
> +**Category: Compliance**
Hi @ejhenry - I do not have stv1 instances but stv2 only, the below screenshot shows the stv2 instances where I have changed the filter to look for text not with stv1. In my commit, I have looked for text not with stv2. 
<img width="745" alt="image" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/61921020/517395be-2f80-407c-b471-0cbf7a967551">

2024-03-29 16:18 UTC, ejhenry commented on docs/content/services/integration/api-management/_index.md
@aarthiem please update the summary table at the top of this page to include your new recommendation. Thanks.

2024-04-04 15:12 UTC, aarthiem commented on docs/content/services/integration/api-management/_index.md
@ejhenry - updated the table, please check

2024-04-04 19:55 UTC, oZakari approved these changes

2024-04-04 19:55 UTC, oZakari requested changes
Just waiting for screenshot as discussed, but otherwise looks good!

2024-04-04 23:30 UTC, aarthiem commented
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/61921020/d966ef7a-d093-441e-865c-d9e833a90937)
<img width="717" alt="Screenshot 2024-04-04 192639" src="https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/61921020/fe0615c4-53b9-4736-a85e-c3be7f1d01e8">
@ejhenry @edknox @oZakari - Please check the screenshot here.

2024-04-05 01:28 UTC, oZakari approved these changes

2024-04-05 01:30 UTC, merged