Updated Log Analytics recommendations based on verification from PG
Azure/Azure-Proactive-Resiliency-Library pull request #349
Opened 2024-03-18 18:57 UTC by judyer28

# Overview/Summary

Updated Log Analytics recommendations based on discussions with the PG.  Original LOG-2 and LOG-3 have been removed. 

## Related Issues/Work Items

[AB#34111](https://dev.azure.com/CSUSolEng/Process%20Guidance/_workitems/edit/34111)

## This PR fixes/adds/changes/removes

1. Update category of LOG-1 to Governance
2. Remove original LOG-2 and LOG-3/
3. Change LOG-4 to LOG-2
4. Change LOG-5 to LOG-3 and update category to Governance

### Breaking Changes

NA

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-03-18 19:34 UTC, ejhenry reviewed
Thanks @judyer28! We're not changing recommendation IDs, so no need to re-number 4 & 5. We found changing IDs was resulting in a lot of confusion.

2024-03-18 20:16 UTC, judyer28 commented
Thanks @ejhenry.  Reverted back to original ID numbers.

2024-03-19 18:40 UTC, oZakari commented on docs/content/services/monitoring/log-analytics/_index.md
> +Data export in a Log Analytics workspace lets you continuously export data to an Azure Storage account.  Protect your Log Analytics workspace data from the unlikely event of a regional failure by con
```suggestion
Data export in a Log Analytics workspace lets you continuously export data to an Azure Storage account.  Protect your Log Analytics workspace data from the unlikely event of a regional failure by continuously exporting to a geo-redundant storage (GRS) or geo-zone-redundant storage (GZRS) account.  This is primarily a recommendation to meet compliance for data retention, but can also be used to integrate the data with other Azure services and tools. 
```

2024-03-19 18:40 UTC, oZakari requested changes
Just a minor addition to the wording for the recommendation if it makes sense to you?

2024-03-19 18:45 UTC, judyer28 commented
Makes sense to me @oZakari.  Thanks for the review and suggestion.

2024-03-19 20:54 UTC, oZakari approved these changes

2024-03-19 20:58 UTC, ejhenry approved these changes
LGTM 👍

2024-03-19 22:44 UTC, merged