Web Application Firewall: Created recommendation for WAF - Review fee…
Azure/Azure-Proactive-Resiliency-Library pull request #36
Opened 2023-05-31 14:27 UTC by min-git

…dback: Added impact column an others

# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2023-05-31 14:44 UTC, lachaves requested changes
Hi Kyoung, 
I tried running hugo server and it fails as the files wa-3.kql, wa-4.kql, wa-7.kql and wa-8.kql are missing. We need those files even if they are empty as it will fail if they are mentioned in the _index.md file but are not present where expected.

2023-06-09 20:46 UTC, rodrigosantosms commented
I added the missing files and validated the Hugo build, approving this one.

2023-06-09 20:48 UTC, rodrigosantosms approved these changes

2023-06-09 20:50 UTC, rodrigosantosms approved these changes

2023-06-09 20:53 UTC, merged

2023-06-12 01:51 UTC, min-git commented
The recommendations for WA-3, WA-4, WA-7 and WA-8 don't have KQL. I removed Azure Resource Graph part of them in index.md and delete the KQL files. Pls review this.