AVD updates
Azure/Azure-Proactive-Resiliency-Library pull request #373
Opened 2024-03-21 00:23 UTC by moisesjgomez

# Overview/Summary

Updates with AVD APRL recommendations.

## Related Issues/Work Items

Replace this with a list of related GitHub Issues and/or ADO Work Items (Internal Only)

- To associate a GitHub Issue, use a [key word](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) preceded with the GitHub issue number.
- To associate an ADO Work Item, use the key word `AB#` succeeded with the [ADO Work Item ID](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## This PR fixes/adds/changes/removes

1. Adds recommendations to AVD
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-03-21 19:29 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +| [AVD-29 App attach should be placed in separate file share; Disaster recovery plan should include App attach storage.](#avd-29---app-attach-should-be-placed-in-separate-file-share-and-disaster-reco
```suggestion
| [AVD-29 App attach should be placed in separate file share; Disaster recovery plan should include App attach storage](#avd-29---app-attach-should-be-placed-in-separate-file-share-and-disaster-recovery-plan-should-include-app-attach-storage)
```

This is a broken link

2024-03-21 19:32 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +| [AVD-32 Ensure the network is resilient](#avd-32---ensure-the-network-is-resilient) | Networking/Connectivity | Medium | Verified | No |
This link is broken, please check and validate within the PR tests.

2024-03-21 19:38 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +| [VM-25 - Do not create more than 2000 Citrix VDA servers per subscription](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/compute/virtual-machines/#vm-25---do-not-create-more-t
```suggestion
| [VM-25 - Do not create more than 2000 Citrix VDA servers per subscription](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/management/subscription/#ms-1---do-not-create-more-than-2000-citrix-vda-servers-per-subscription) | Application Resiliency | High | Verified | Yes |
```

2024-03-21 19:41 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
>  {{< table style="table-striped" >}}
For all new recommendations, please ensure that category names align to what is specified in the contribution guide. https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#recommendation-categories

2024-03-21 19:44 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Scaling plans exist per region assigned to host pools within the region and can become inaccessible in case of regional failure. A secondary scaling plan should be created with a secondary region to
```suggestion
Each region has its own scaling plans assigned to host pools within that region. However, these plans can become inaccessible if there's a regional failure. To mitigate this risk, it's advisable to create a secondary scaling plan in another region
```

2024-03-21 19:44 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Scaling plans exist per region assigned to host pools within the region and can become inaccessible in case of regional failure. A secondary scaling plan should be created with a secondary region to
A little bit confusing on the sentence structure, could you take a look at my suggestion and/or reword for clarity?

2024-03-21 19:49 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +### AVD-12 - Keep detailed documentation of all AVD and shared services based on BCDR strategy detailing failover scenarios covered based on agreements
Can we reference this recommendation in place of this: https://azure.github.io/Azure-Proactive-Resiliency-Library/well-architected/2-design/#wads-7---design-a-bcdr-strategy-that-will-help-to-meet-the-business-requirements

2024-03-21 19:51 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Global URLs confirmed whitelisted. UDP/TURN ports open and accessible.
Can you please reword for clarity as it's a little unclear for me what with how the sentences are worded.

2024-03-21 19:52 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Set up secondary server in staging mode for Entra Connect for syncing to Entra in case of primary server outage.
```suggestion
For optimal performance and reliability, Entra ID Connect is best operated within Azure's environment, although it can be hosted on-premises if necessary. As part of a hybrid setup, it's advisable to establish secondary VMs in staging mode to prepare for failover scenarios.

To ensure continuity, set up a secondary server for Entra Connect in staging mode. This secondary server will serve as a backup, ready to sync with Entra in the event of a primary server outage.
```

2024-03-21 19:52 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +### AVD-14 - Ensure Secondary Entra ID connect synchronization server
```suggestion
### AVD-14 - Incorporate Secondary Entra ID connect synchronization server
```

2024-03-21 19:54 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Hybrid - Each Azure region with AVD hosts should have ADDS DCs (IaaS VMs) in Azure and use Availability Sets or Zones for resiliency across single Datacenter or Region. Mitigates dependency on ER/VPN
```suggestion
Hybrid - Each Azure region with AVD hosts should have ADDS DCs (IaaS VMs) in Azure and use Availability Sets or Zones for resiliency across single Datacenter or Region. This mitigates dependency on ER/VPN/Inter-Azure dependencies.
```

2024-03-21 19:54 UTC, swathibhat1 reviewed
Review completed.

2024-03-21 20:47 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Scheduled AVD agent updates on the host pool.
Is this sentence needed or could it be incorporated differently?

2024-03-22 02:27 UTC, oZakari requested changes

2024-03-22 02:27 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +| [ST-1 - Ensure that Storage Account configuration is at least Zone redundant](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/storage/storage-account/#st-1---ensure-that-storage
For all recommendations that are referenced, can you ensure fields match, specifically for the state column in this case.

2024-03-22 02:27 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Each region has its own scaling plans assigned to host pools within that region. However, these plans can become inaccessible if there's a regional failure. To mitigate this risk, it's advisable to c
```suggestion
Each region has its own scaling plans assigned to host pools within that region. However, these plans can become inaccessible if there's a regional failure. To mitigate this risk, it's advisable to create a secondary scaling plan in another region.
```

2024-03-22 02:27 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Ensure each Region with session host has multiple domain controllers in the same region to support adjustments based on your business requirements. To handle a large number of users, consider scaling
Please adjust guidance as `support adjustments` is not specific enough and the second sentence doesn't appear to align to this specific recommendation.

2024-03-22 02:27 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +ADDS Integrated DNS/other should target Secondary/Tertiary customer DNS across multi-region zones. If using custom DNS, ensure there are redundant DNS servers to avoid a single point of failure.
```suggestion
Active Directory Domain Services (AD DS) integrated DNS/other should target Secondary/Tertiary customer DNS across multi-region zones. If using custom DNS, ensure there are redundant DNS servers to avoid a single point of failure.
```

2024-03-22 02:27 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +### AVD-18 - Create new version of updated image and replace session hosts rather than update host directly
```suggestion
### AVD-18 - Create updated image version and replace session hosts rather than updating host directly
```

2024-03-22 02:27 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +- [Learn More](https://learn.microsoft.com/en-US/azure/virtual-desktop/set-up-service-alerts)
This link points to alerting and not log aggregation with Log Analytics.

2024-03-22 02:31 UTC, oZakari commented
Hi @moisesjgomez, could you also update the PR form to include any relevant work items for tracking.

2024-03-22 18:00 UTC, swathibhat1 commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +| [AVD-32 Ensure the network is resilient](#avd-32---ensure-the-network-is-resilient) | Networking/Connectivity | Medium | Verified | No |
Reviewed. The URLs seem to be working.

2024-03-22 18:06 UTC, swathibhat1 commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +| [ST-1 - Ensure that Storage Account configuration is at least Zone redundant](https://azure.github.io/Azure-Proactive-Resiliency-Library/services/storage/storage-account/#st-1---ensure-that-storage
Moises has applied the changes.

2024-03-22 18:12 UTC, swathibhat1 commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +- [Learn More](https://learn.microsoft.com/en-US/azure/virtual-desktop/set-up-service-alerts)
Applied the changes.

2024-03-22 18:19 UTC, swathibhat1 commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +Ensure each Region with session host has multiple domain controllers in the same region to support adjustments based on your business requirements. To handle a large number of users, consider scaling
Moises has added the changes.

2024-03-23 00:22 UTC, swathibhat1 reviewed
Reviewed. Request to be merged. Thank you.

2024-03-25 16:35 UTC, swathibhat1 commented on docs/content/services/specialized-workloads/azure-virtual-desktop/_index.md
> +### AVD-12 - Keep detailed documentation of all AVD and shared services based on BCDR strategy detailing failover scenarios covered based on agreements
We have included WADS-7 recommendation in addition to the above, would it be better if we retain the above since it's AVD specific?

2024-03-25 17:28 UTC, ejhenry commented
Hi @moisesjgomez, thanks for the contribution! Looking through the recommendations in the PR, several of them don't seem to align with our guidance in the contribution guide about writing recommendations that are actionable for a CSA within the context of a reliability assessment. For example, being a non-AVD expert, I know I would struggle with AVD-13,17,18,22,25,27,32,35. Is it possible to re-write the recommendations to make them clearer with respect to reliability and more actionable? 

https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing/#writing-a-recommendation

Also, some of the recommendations, such as AVD-30 and 34, look to be redundant with existing ARPL recommendations for those services.

cc @swathibhat1 @oZakari

2024-03-26 16:59 UTC, swathibhat1 reviewed
Review completed. PR tests passed. Recommended changes included. Request to approve.

2024-03-26 23:48 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-2/avd-2.fix
What is the reason for adding a .fix file here?

2024-03-26 23:48 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-24/avd-24.kql
Please use one of the approved values form the contribution guide for this file

2024-03-26 23:48 UTC, ejhenry commented on docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-25/avd-25.kql
Please use one of the approved values form the contribution guide for this file

2024-03-27 02:03 UTC, oZakari approved these changes
Good on my end once Erik's changes requests are approved.

2024-03-27 14:08 UTC, moisesjgomez commented on docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-24/avd-24.kql
Updated

2024-03-27 14:14 UTC, swathibhat1 reviewed
Reviewed the changes and approved on my end. Request for approval and merge.

2024-03-27 16:38 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-2/avd-2.fix
I've removed the avd-2.fix file and replaced with avd-2.kql file which is what is currently referenced in _index.md file anyways. We only use .fix files for pre-existing queries that had issues, and these are not displayed publicly within APRL.

2024-03-27 16:38 UTC, merged