Guidance for legacy workspaces & alternate VM SKUs
Azure/Azure-Proactive-Resiliency-Library pull request #429
Opened 2024-04-01 15:58 UTC by SenthuranSivananthan

# Overview/Summary

Added two Azure Databricks Guidance:

- DBW-29 - Migrate Legacy Workspaces
- DBW-30 - Define alternate VM SKUs

## Related Issues/Work Items

N/A

## This PR fixes/adds/changes/removes

- Add guidance for DBW-29 - Migrate Legacy Workspaces
- Add guidance for DBW-30 - Define alternate VM SKUs

### Breaking Changes

None

## As part of this Pull Request I have

- [x] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x] Ensured PR tests are passing
- [x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-04-02 20:26 UTC, Dost2010 approved these changes

2024-04-02 21:44 UTC, rodrigosantosms requested changes
Please remove all links from the "Guidance/Description", they should only exist in the "Reference Links" section, otherwise it could break some of our automations.

2024-04-05 12:39 UTC, SenthuranSivananthan commented
@oZakari / @rodrigosantosms - links in the descriptions have been removed.  Are there other changes to make?

2024-04-05 14:47 UTC, rodrigosantosms approved these changes
I've made some changes to avoid breaking our automation. I'll sync with Senthu later about the changes. PR Approved.

2024-04-05 14:51 UTC, merged