Fixed a few typos and deleted quear that did not work
Azure/Azure-Proactive-Resiliency-Library pull request #441
Opened 2024-04-04 13:16 UTC by yshafner

# Overview/Summary

I deleted a query that was broken and updated the table accordingly 
## Related Issues/Work Items

ADO work item: https://dev.azure.com/CSUSolEng/Accelerator%20-%20AVD/_workitems/edit/34527

## This PR fixes/adds/changes/removes

1. AVD 1 removed query
2. Updated table accordingly

### Breaking Changes

1.NA

## As part of this Pull Request I have

- [x ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [x ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [x ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [x ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [x ] Ensured PR tests are passing
- [ x] Performed testing and provided evidence (e.g. screenshot of output) for any changes associated to ARG queries and/or scripts
- [ x] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2024-04-04 15:31 UTC, Dost2010 approved these changes

2024-04-04 15:56 UTC, oZakari requested changes

2024-04-04 15:56 UTC, oZakari commented on docs/content/services/specialized-workloads/azure-virtual-desktop/code/avd-2/avd-2.kql
@yshafner has something changed with the information available in ARG that this query can now have the correct data returned? Just want to make sure, as usually people who use the //cannot-be-validated-with-arg have determined that the data is not available within arg?

2024-04-05 14:50 UTC, rodrigosantosms approved these changes

2024-04-05 15:43 UTC, merged