Updated with latest APRL recommendations.
Azure/Azure-Proactive-Resiliency-Library pull request #79
Opened 2023-09-13 19:52 UTC by jimays-avila

# Overview/Summary

Replace this with a brief description of what this Pull Request fixes, changes, etc.

## This PR fixes/adds/changes/removes

1. *Replace me*
2. *Replace me*
3. *Replace me*

### Breaking Changes

1. *Replace me*
2. *Replace me*

## As part of this Pull Request I have

- [ ] Read the [Contribution Guide](https://azure.github.io/Azure-Proactive-Resiliency-Library/contributing) and ensured this PR is compliant with the guide
- [ ] Checked for duplicate [Pull Requests](https://github.com/Azure/Azure-Proactive-Resiliency-Library/pulls)
- [ ] Associated it with relevant [GitHub Issues](https://github.com/Azure/Azure-Proactive-Resiliency-Library/issues) or ADO Work Items (Internal Only)
- [ ] Ensured my code/branch is up-to-date with the latest changes in the `main` [branch](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main)
- [ ] Ensured PR tests are passing
- [ ] Updated relevant and associated documentation (e.g. Contribution Guide, Docs etc.)

2023-09-14 01:58 UTC, rodrigosantosms requested changes
PLease see the required changes for each file/line.

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-9/appgw-9.kql
add the following as a comment instead TBD.

// under development

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-8/appgw-8.kql
Query results should follow the following standard
"recommendationId", Name, Id
or
"recommendationId", Name, Id, AnyAdditionalParameters_if_Any

See, VMs, Storage Accounts, Load Balancers for some examples. The project will look like this:

| project recommendationId = "vm-1", name, id

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-7/appgw-7.kql
Query results should follow the following standard
"recommendationId", Name, Id
or
"recommendationId", Name, Id, AnyAdditionalParameters_if_Any

See, VMs, Storage Accounts, Load Balancers for some examples. The project will look like this:

| project recommendationId = "vm-1", name, id

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-6/appgw-6.kql
Query results should follow the following standard
"recommendationId", Name, Id
or
"recommendationId", Name, Id, AnyAdditionalParameters_if_Any

See, VMs, Storage Accounts, Load Balancers for some examples. The project will look like this:

| project recommendationId = "vm-1", name, id

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-4/appgw-4.kql
Query results should follow the following standard
"recommendationId", Name, Id
or
"recommendationId", Name, Id, AnyAdditionalParameters_if_Any

See, VMs, Storage Accounts, Load Balancers for some examples. The project will look like this:

| project recommendationId = "vm-1", name, id

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-3/appgw-3.kql
Query results should follow the following standard
"recommendationId", Name, Id
or
"recommendationId", Name, Id, AnyAdditionalParameters_if_Any

See, VMs, Storage Accounts, Load Balancers for some examples. The project will look like this:

| project recommendationId = "vm-1", name, id

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-2/appgw-2.kql
Query results should follow the following standard
"recommendationId", Name, Id
or
"recommendationId", Name, Id, AnyAdditionalParameters_if_Any

See, VMs, Storage Accounts, Load Balancers for some examples. The project will look like this:

| project recommendationId = "vm-1", name, id

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-1/appgw-1.kql
Query results should follow the following standard
"recommendationId", Name, Id
or
"recommendationId", Name, Id, AnyAdditionalParameters_if_Any

See, VMs, Storage Accounts, Load Balancers for some examples. The project will look like this:

| project recommendationId = "vm-1", name, id

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/code/appgw-5/appgw-5.kql
add the following as a comment instead TBD.

// under development

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/_index.md
> +{{< code lang="sql" file="code/appgw-1/appgw-9.kql" >}} {{< /code >}}
Folder name is incorrect, it should be appgw-9

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/_index.md
> +### APPGW-9 - Ensure Application Gateway Subnet is using a 24 subnet mask
Add the / before 24.

### APPGW-9 - Ensure Application Gateway Subnet is using a /24 subnet mask

2023-09-14 01:58 UTC, rodrigosantosms commented on docs/content/services/networking/Application Gateway/_index.md
> +| [APPGW-9 - Ensure Application Gateway Subnet is using a 24 subnet mask](#appgw-9---ensure-application-gateway-subnet-is-using-a-24-subnet-mask)                       |  High    | Preview  | Yes |
Add the / before 24.

### APPGW-9 - Ensure Application Gateway Subnet is using a /24 subnet mask

2023-09-15 13:22 UTC, jimays-avila commented on docs/content/services/networking/Application Gateway/code/appgw-9/appgw-9.kql
I have updated all queries to match the recommendations as requested.

2023-09-15 13:24 UTC, jimays-avila commented
@rodrigosantosms can you please review the changes.

2023-10-04 02:48 UTC, oZakari commented
Hey @jimays-avila, you have some merge conflicts due to the [changes](https://github.com/Azure/Azure-Proactive-Resiliency-Library/tree/main/docs/content/services/networking/application-gateway/code) that were made for standardizing the service folder names and using CAF abbreviations. Once you correct that, let me know and I can review and merge into main for you,

2023-10-04 20:32 UTC, jimays-avila commented
@oZakari I recently made changes based on those factors. Are they not reflecting as I made those updates yesterday.  Can this PR just be cancelled and I can submit a new one once all the changes have been made or will the new changes updated here as well?

2023-10-05 05:29 UTC, oZakari commented
@jimays-avila  They are not reflecting in your current branch atm. Below is your current branch:

![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/30884663/476a616a-8055-4670-aba2-ca4b5476d820)

Here is what the current upstream main branch looks like:
![image](https://github.com/Azure/Azure-Proactive-Resiliency-Library/assets/30884663/ee80dad9-4fd1-4c72-ab10-d487218a637e)

A standard git merge should detect the renamed files, but there are some changes within the index.md that you may need to go through on a case-by-case basis. There are a bunch of tools to help with this if you want to avoid the command line and my favorite is https://www.gitkraken.com/

However, if you want to mess with it too much. You could create a new branch from upstream main and then just copy your changes in this time since it looks like the KQL queries were the only things modified. 

I'm happy to help as well, so feel free to ping me in Teams.

2023-10-06 19:23 UTC, jimays-avila commented
I made the necessary changes to align with the naming convention of the folders and files and kql queries.

2023-10-09 16:03 UTC, oZakari commented
Currently working with @jimays-avila on resolving merge conflicts.

2023-10-10 17:58 UTC, oZakari requested changes

2023-10-10 17:58 UTC, oZakari commented on docs/content/services/networking/application-gateway/_index.md
Please change these back to AGW acronym

2023-10-10 17:58 UTC, oZakari commented on docs/content/services/compute/virtual-machine-scale-sets/code/vmss-10/vmss-10.kql
> +| project VMSSName, ImageReference
Please add the standard query columns: id, name and us param1 in place of imageReference.

2023-10-10 17:58 UTC, oZakari commented on docs/content/services/networking/application-gateway/code/agw-8/agw-8.kql
Please add the standard query columns: id, name, etc

2023-10-10 17:58 UTC, oZakari commented on docs/content/services/networking/application-gateway/code/agw-7/agw-7.kql
Please add the standard query columns: id, name, etc

2023-10-10 17:59 UTC, jimays-avila commented on docs/content/services/compute/virtual-machine-scale-sets/code/vmss-10/vmss-10.kql
> +| project VMSSName, ImageReference
Will make changes now.

2023-10-10 19:58 UTC, jimays-avila commented on docs/content/services/networking/application-gateway/_index.md
> -
I will review this.

2023-10-17 18:22 UTC, jimays-avila reviewed
Are there any other changes that need to be made

2023-10-17 19:17 UTC, oZakari approved these changes

2023-10-17 19:58 UTC, merged